spring:
  application:
    name: keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/Study
          jwk-set-uri: http://localhost:9090/realms/Study/protocol/openid-connect/certs
